### ISSUE TITLE
Not working with latest netlify-cli

### ISSUE THREAD

**Issue by hypnoboutique** [whitep4nth3r/nextjs-advanced-middleware-on-netlify-demo#3]
Hello 👋,

I know this example application is quite old now but since there is not a great deal of info out there regarding advanced middleware except for this repo and the tutorial [here](https://www.netlify.com/blog/rewrite-html-transform-page-props-in-nextjs/), I thought it was worth mentioning two fairly major issues I encountered when trying to reproduce:

1. Using the latest [netlify-cli](https://www.npmjs.com/package/netlify-cli) package results in an error: `Reading or writing files with Edge Functions is not supported yet`
2. Using an older version of netlify-cli (netlify-cli/12.2.9, although I don't know when this changed) this project runs on Next@12 only. On updating to Next@13, the middleware.ts file was ignored. 

### Repro:
- Pull fresh from this repo
- Globally install latest (at time of writing) netlify-cli `npm i -g netlify-cli@15.0.2` or `npm i -g netlify-cli@latest`
- Run `netlify dev`

### Notes
I was super confused by the mention of Deno in the tutorial. In another project, I'm using Netlify edge functions _another_ documented way 😏 (via a `netlify.toml` file; funcs are in `netlify/edge-functions`) and these DO use Deno, and you can't use npm imports like we have here but use imports like `import type {Context} from "https://edge.netlify.com";`

If you had any up to date intel about advanced middleware (specifically dom/prop editing) with Next@13, I would overjoyed to hear it! If not, please feel free to tell me to jog on (or maybe even point me in a direction 🙏 )

Ta!

**Comment by whitep4nth3r** [comment]
Looking into this for you!

**Comment by whitep4nth3r** [comment]
The next-runtime used in this project (4.17) is too old and uses the filesystem in local development — this was a hangover from when we were developing the feature! 

We removed filesystem access in edge functions from the CLI in one of the latest major versions, because it is also not available in production. Updating the next-runtime to 4.32 or newer should fix the problem.

Let me know how you get on!

**Comment by hypnoboutique** [comment]
Thanks so much for the quick response and resolution.

Do you know if there is any expectation to support Next.JS@13 with the advanced middleware feature? The introduction of the `/app` directory as a stable feature means page props are no longer a "thing" 🙁

**Comment by whitep4nth3r** [comment]
We definitely want to support Next.js 13 as fully as we can. The repo for [Netlify's Next Runtime](https://github.com/netlify/next-runtime) is open source, so feel free to submit an issue per your particular use case.
